#!/bin/env python3
import sys
import time
name=sys.argv[1]
current_time = time.strftime("%Y-%m-%d %H:%m:%S %Z")
print("hello "+name," right now the time is "+current_time)
                                                           
